# Generated by Django 5.1.4 on 2026-07-06 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('camps', '0006_alter_participant_options_and_more'),
        ('recipes', '0007_ingredient_price_ingredient_price_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beleg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Handyfoto des Kassenbons oder der A4-Rechnung', upload_to='belege/%Y/%m/', verbose_name='Belegfoto')),
                ('status', models.CharField(choices=[('neu', 'Neu'), ('analysiert', 'Analysiert'), ('geprueft', 'Geprüft'), ('fehler', 'Fehler bei Analyse')], default='neu', max_length=20)),
                ('haendler', models.CharField(blank=True, max_length=200, verbose_name='Händler / Laden')),
                ('kaufdatum', models.DateField(blank=True, null=True, verbose_name='Kaufdatum')),
                ('gesamtbetrag', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Gesamtbetrag (€)')),
                ('analyse_rohdaten', models.JSONField(blank=True, null=True, verbose_name='Analyse-Rohdaten (JSON)')),
                ('analyse_fehler', models.TextField(blank=True, verbose_name='Fehlermeldung der Analyse')),
                ('analysiert_am', models.DateTimeField(blank=True, null=True)),
                ('hochgeladen_am', models.DateTimeField(auto_now_add=True)),
                ('notiz', models.CharField(blank=True, max_length=300, verbose_name='Notiz')),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belege', to='camps.camp', verbose_name='Freizeit')),
                ('hochgeladen_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='belege_hochgeladen', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Beleg',
                'verbose_name_plural': 'Belege',
                'ordering': ['-hochgeladen_am'],
            },
        ),
        migrations.CreateModel(
            name='BelegPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sortierung', models.PositiveIntegerField(default=0)),
                ('text_original', models.CharField(blank=True, max_length=300, verbose_name='Bontext (wie gedruckt)')),
                ('artikel_name', models.CharField(max_length=200, verbose_name='Artikel')),
                ('menge', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Menge')),
                ('einheit', models.CharField(blank=True, choices=[('g', 'g'), ('kg', 'kg'), ('ml', 'ml'), ('l', 'l'), ('Stk', 'Stk'), ('EL', 'EL'), ('TL', 'TL'), ('Pck', 'Pck'), ('Bd', 'Bd')], max_length=10, verbose_name='Einheit')),
                ('gesamtpreis', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Zeilensumme (€)')),
                ('grundpreis', models.DecimalField(blank=True, decimal_places=4, help_text='Preis je Grundpreis-Einheit, z.B. 8,73 für 8,73 €/kg', max_digits=10, null=True, verbose_name='Grundpreis (€)')),
                ('grundpreis_einheit', models.CharField(blank=True, choices=[('kg', 'kg'), ('l', 'l'), ('Stk', 'Stk'), ('Pck', 'Pck')], max_length=10, verbose_name='Grundpreis-Einheit')),
                ('hinweis', models.CharField(blank=True, help_text='z.B. Pfand, Rabatt, unsichere Erkennung', max_length=200, verbose_name='Hinweis')),
                ('ist_uebernommen', models.BooleanField(default=False, verbose_name='Preis übernommen')),
                ('uebernommen_am', models.DateTimeField(blank=True, null=True)),
                ('beleg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positionen', to='rechnungen.beleg')),
                ('ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beleg_positionen', to='recipes.ingredient', verbose_name='Zutat')),
            ],
            options={
                'verbose_name': 'Beleg-Position',
                'verbose_name_plural': 'Beleg-Positionen',
                'ordering': ['beleg', 'sortierung', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Preishistorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preis', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Preis (€)')),
                ('einheit', models.CharField(choices=[('g', 'g'), ('kg', 'kg'), ('ml', 'ml'), ('l', 'l'), ('Stk', 'Stk'), ('EL', 'EL'), ('TL', 'TL'), ('Pck', 'Pck'), ('Bd', 'Bd')], max_length=10, verbose_name='Preis-Einheit')),
                ('haendler', models.CharField(blank=True, max_length=200, verbose_name='Händler')),
                ('kaufdatum', models.DateField(blank=True, null=True, verbose_name='Kaufdatum')),
                ('erfasst_am', models.DateTimeField(auto_now_add=True)),
                ('beleg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preiseintraege', to='rechnungen.beleg')),
                ('erfasst_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preishistorie', to='recipes.ingredient', verbose_name='Zutat')),
            ],
            options={
                'verbose_name': 'Preishistorie-Eintrag',
                'verbose_name_plural': 'Preishistorie',
                'ordering': ['-erfasst_am'],
            },
        ),
    ]
