# Generated by Django 5.1.4 on 2026-07-08 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rechnungen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kostenkategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('sortierung', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Kostenkategorie',
                'verbose_name_plural': 'Kostenkategorien',
                'ordering': ['sortierung', 'name'],
            },
        ),
        migrations.AddField(
            model_name='beleg',
            name='kategorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='belege', to='rechnungen.kostenkategorie', verbose_name='Kostenkategorie'),
        ),
    ]
