# Generated by Django 5.1.4 on 2026-07-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rechnungen', '0003_standard_kategorien'),
    ]

    operations = [
        migrations.AddField(
            model_name='beleg',
            name='nur_preiserfassung',
            field=models.BooleanField(default=False, help_text='Nur zur Preiserfassung (z.B. alte Belege) -- zählt nicht zu den Ist-Kosten der Freizeit.', verbose_name='Nicht für aktuelle Freizeit'),
        ),
    ]
