# Generated by Django 5.1.4 on 2026-07-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rechnungen', '0004_beleg_nur_preiserfassung'),
    ]

    operations = [
        migrations.AddField(
            model_name='belegposition',
            name='stueckpreis',
            field=models.DecimalField(blank=True, decimal_places=4, help_text="Bei stückbasierten Bon-Zeilen (z.B. '13 ST - 1 ST 4,29') der Einzelpreis. Wird bei stückbasiert bepreisten Zutaten (Stk/Pck) für die Übernahme genutzt, statt aus kg/l umzurechnen.", max_digits=10, null=True, verbose_name='Preis je Stück (€)'),
        ),
    ]
