# Generated by Django 5.1.4 on 2026-08-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rechnungen', '0005_belegposition_stueckpreis'),
    ]

    operations = [
        migrations.AddField(
            model_name='beleg',
            name='preise_netto',
            field=models.BooleanField(default=False, help_text='Großhandelsrechnungen (z.B. Wasgau C+C) drucken Nettopreise mit Steuercode je Position. Bei der Preisübernahme wird dann anhand des MwSt-Satzes der Position auf brutto umgerechnet, damit alle Preise in der Datenbank vergleichbar sind (Supermarkt-Bons sind brutto).', verbose_name='Nettopreise'),
        ),
        migrations.AddField(
            model_name='belegposition',
            name='artikelnummer',
            field=models.CharField(blank=True, max_length=50, verbose_name='Artikelnummer (Händler)'),
        ),
        migrations.AddField(
            model_name='belegposition',
            name='ean',
            field=models.CharField(blank=True, max_length=20, verbose_name='EAN/GTIN'),
        ),
        migrations.AddField(
            model_name='belegposition',
            name='mwst_satz',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Steuersatz der Position (7 oder 19). Bei Netto-Belegen Pflicht für die Preisübernahme, da netto -> brutto umgerechnet wird.', max_digits=4, null=True, verbose_name='MwSt-Satz (%)'),
        ),
    ]
