# Generated by Django 5.1.4 on 2026-07-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_must_change_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin (root)'), ('leitung', 'Leitung'), ('supervisor', 'Betreuer'), ('kitchen', 'Küche'), ('staff', 'Mitarbeiter')], default='staff', max_length=20),
        ),
    ]
