# Generated by Django 5.1.4 on 2026-05-14 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camps", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="camp",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="campday",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="intolerance_notes",
            field=models.TextField(
                blank=True,
                help_text="Fuer alles, was nicht in die Checkboxen passt",
                verbose_name="Zusatzhinweise Unvertraeglichkeiten",
            ),
        ),
    ]
