# Generated by Django 5.1.4 on 2026-05-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camps", "0002_alter_camp_id_alter_campday_id_alter_participant_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="intolerance_notes",
            field=models.TextField(
                blank=True,
                help_text="Für alles, was nicht in die Checkboxen passt",
                verbose_name="Zusatzhinweise Unverträglichkeiten",
            ),
        ),
    ]
