# Generated by Django 5.1.4 on 2026-06-07 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camps", "0004_participant_date_of_birth"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="participant",
            options={
                "ordering": ["last_name", "first_name"],
                "verbose_name": "Teili / Betreuer",
                "verbose_name_plural": "Teili / Betreuer",
            },
        ),
        migrations.AlterField(
            model_name="camp",
            name="participant_count",
            field=models.PositiveIntegerField(
                default=100, verbose_name="Teilianzahl (geplant)"
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="person_type",
            field=models.CharField(
                choices=[("participant", "Teili"), ("supervisor", "Betreuer")],
                default="participant",
                max_length=20,
                verbose_name="Typ",
            ),
        ),
    ]
