# Generated by Django 5.1.4 on 2026-06-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camps", "0005_alter_participant_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="participant",
            options={
                "ordering": ["last_name", "first_name"],
                "verbose_name": "Teilnehmer / Betreuer",
                "verbose_name_plural": "Teilnehmer / Betreuer",
            },
        ),
        migrations.AlterField(
            model_name="camp",
            name="participant_count",
            field=models.PositiveIntegerField(
                default=100, verbose_name="Teilnehmeranzahl (geplant)"
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="person_type",
            field=models.CharField(
                choices=[("participant", "Teilnehmer"), ("supervisor", "Betreuer")],
                default="participant",
                max_length=20,
                verbose_name="Typ",
            ),
        ),
    ]
