# Generated by Django 5.1.4 on 2026-05-14 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feedbackentry",
            options={
                "verbose_name": "Feedbackeintrag",
                "verbose_name_plural": "Feedbackeinträge",
            },
        ),
        migrations.AlterField(
            model_name="feedbackentry",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="feedbackentry",
            name="rating",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "😞 Sehr schlecht"),
                    (2, "😕 Schlecht"),
                    (3, "😐 Okay"),
                    (4, "🙂 Gut"),
                    (5, "😄 Sehr gut"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="feedbackform",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
