# Generated by Django 5.1.4 on 2026-07-29 21:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0006_alter_participant_options_and_more'),
        ('feedback', '0002_alter_feedbackentry_options_alter_feedbackentry_id_and_more'),
        ('recipes', '0007_ingredient_price_ingredient_price_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackform',
            name='camp',
        ),
        migrations.RemoveField(
            model_name='feedbackform',
            name='day',
        ),
        migrations.CreateModel(
            name='FeedbackSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_comment', models.TextField(blank=True, verbose_name='Allgemeines Feedback')),
                ('session_hash', models.CharField(blank=True, editable=False, max_length=64)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Abgegeben am')),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_submissions', to='camps.camp', verbose_name='Freizeit')),
            ],
            options={
                'verbose_name': 'Feedbackabgabe',
                'verbose_name_plural': 'Feedbackabgaben',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='MealRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(blank=True, max_length=200, verbose_name='Gericht')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Bewertung (1-10)')),
                ('comment', models.TextField(blank=True, verbose_name='Feedback zum Gericht')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_ratings', to='camps.campday', verbose_name='Tag')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.recipe', verbose_name='Hauptgericht')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='feedback.feedbacksubmission', verbose_name='Feedbackabgabe')),
            ],
            options={
                'verbose_name': 'Gerichtbewertung',
                'verbose_name_plural': 'Gerichtbewertungen',
                'ordering': ['day__date'],
            },
        ),
        migrations.DeleteModel(
            name='FeedbackEntry',
        ),
        migrations.DeleteModel(
            name='FeedbackForm',
        ),
    ]
