# Generated by Django 5.1.4 on 2026-05-14 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0002_daymeal"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="warmmeal",
            options={
                "ordering": ["day__date"],
                "verbose_name": "Abendessen (alt)",
                "verbose_name_plural": "Abendessen (alt)",
            },
        ),
        migrations.AlterField(
            model_name="breadplan",
            name="bread_type",
            field=models.CharField(blank=True, default="Mischbrot", max_length=100),
        ),
        migrations.AlterField(
            model_name="breadplan",
            name="breakfast_loaves",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name="breadplan",
            name="evening_loaves",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name="breadplan",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="breadplan",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="breadplan",
            name="rolls_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="breadplan",
            name="topping_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="breadplan",
            name="use_rolls",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="daymeal",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="daymeal",
            name="person_override",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Leer = alle anwesenden Personen des Tages",
                null=True,
                verbose_name="Personenzahl (manuell)",
            ),
        ),
        migrations.AlterField(
            model_name="warmmeal",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="warmmeal",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="warmmeal",
            name="person_override",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
