# Generated by Django 5.1.4 on 2026-06-07 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0004_fruehstueckconfig"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fruehstueckconfig",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
