# Generated by Django 5.1.4 on 2026-06-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0007_generalingredient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brotconfig",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="generalingredient",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
