# Generated by Django 5.1.4 on 2026-06-18 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camps", "0006_alter_participant_options_and_more"),
        ("meals", "0008_alter_brotconfig_id_alter_generalingredient_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="FruitConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount_apfel",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Äpfel (Stück)"
                    ),
                ),
                (
                    "weight_apfel",
                    models.FloatField(blank=True, null=True, verbose_name="Äpfel (kg)"),
                ),
                (
                    "amount_banane",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Bananen (Stück)"
                    ),
                ),
                (
                    "weight_banane",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Bananen (kg)"
                    ),
                ),
                (
                    "amount_birne",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Birnen (Stück)"
                    ),
                ),
                (
                    "weight_birne",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Birnen (kg)"
                    ),
                ),
                (
                    "amount_nektarine",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Nektarinen (Stück)"
                    ),
                ),
                (
                    "weight_nektarine",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Nektarinen (kg)"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "camp",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fruit_config",
                        to="camps.camp",
                    ),
                ),
            ],
            options={
                "verbose_name": "Obst Konfiguration",
                "verbose_name_plural": "Obst Konfigurationen",
            },
        ),
    ]
