# Generated by Django 5.1.4 on 2026-06-19 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camps", "0006_alter_participant_options_and_more"),
        ("meals", "0009_fruitconfig"),
        ("recipes", "0006_alter_recipeingredient_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalingredient",
            name="category",
            field=models.CharField(
                choices=[
                    ("allgemein", "Allgemein"),
                    ("betreueressen", "Betreueressen"),
                ],
                default="allgemein",
                max_length=20,
                verbose_name="Kategorie",
            ),
        ),
        migrations.AddField(
            model_name="generalingredient",
            name="day",
            field=models.ForeignKey(
                blank=True,
                help_text="Nur für category='betreueressen': Tag, an dessen Liefertag die Zutat ankommen soll.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="general_ingredients",
                to="camps.campday",
                verbose_name="Tag (nur Betreueressen)",
            ),
        ),
        migrations.CreateModel(
            name="SupervisorMealReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supervisor_meal_reference",
                        to="camps.campday",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="as_supervisor_meal_reference",
                        to="recipes.recipe",
                        verbose_name="Bezugsrezept (Hauptgericht)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Betreueressen Bezugsrezept",
                "verbose_name_plural": "Betreueressen Bezugsrezepte",
            },
        ),
    ]
