# Generated by Django 5.1.4 on 2026-06-19 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0010_generalingredient_category_generalingredient_day_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SupervisorMealReference",
        ),
    ]
