# Generated by Django 5.1.4 on 2026-06-29 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camps", "0006_alter_participant_options_and_more"),
        ("meals", "0011_delete_supervisormealreference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generalingredient",
            name="category",
            field=models.CharField(
                choices=[
                    ("allgemein", "Allgemein"),
                    ("betreueressen", "Betreueressen"),
                    ("alternative", "Alternative"),
                ],
                default="allgemein",
                max_length=20,
                verbose_name="Kategorie",
            ),
        ),
        migrations.AlterField(
            model_name="generalingredient",
            name="day",
            field=models.ForeignKey(
                blank=True,
                help_text="Nur für category='betreueressen' oder 'alternative': Tag, an dessen Liefertag die Zutat ankommen soll.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="general_ingredients",
                to="camps.campday",
                verbose_name="Tag (nur Betreueressen/Alternative)",
            ),
        ),
    ]
