# Generated by Django 5.1.4 on 2026-07-01 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camps", "0006_alter_participant_options_and_more"),
        ("meals", "0012_alter_generalingredient_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NussNougatConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "g_per_halbweck",
                    models.FloatField(
                        blank=True,
                        help_text="Gramm Nuss-Nougat-Creme pro Halbweck (eine Seite eines Doppelwecks). Gesamtmenge = g_pro_Halbweck × 2 × Anzahl_Doppelweck.",
                        null=True,
                        verbose_name="g pro Halbweck",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "camp",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nuss_nougat_config",
                        to="camps.camp",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nuss-Nougat Konfiguration",
            },
        ),
    ]
