# Generated by Django 5.1.4 on 2026-07-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0013_nussnougatconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="fruehstueckconfig",
            name="halbweck_cheese",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="fruehstueckconfig",
            name="halbweck_fleischkaese",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="fruehstueckconfig",
            name="halbweck_fleischwurst",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="fruehstueckconfig",
            name="halbweck_salami",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
