# Generated by Django 5.1.4 on 2026-07-02 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Wochenplan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "camp_id",
                    models.IntegerField(
                        help_text="ID des Camps aus der bestehenden Camp-Tabelle",
                        verbose_name="Camp-ID",
                    ),
                ),
                ("titel", models.CharField(max_length=200, verbose_name="Titel")),
                ("erstellt_am", models.DateTimeField(auto_now_add=True)),
                ("geaendert_am", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Wochenplan",
                "verbose_name_plural": "Wochenplaene",
                "ordering": ["camp_id", "titel"],
            },
        ),
        migrations.CreateModel(
            name="MobileUserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "force_password_reset",
                    models.BooleanField(
                        default=True,
                        help_text="Wenn True, muss der Nutzer beim naechsten Login ein neues Passwort setzen.",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mobile_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Mobile Nutzerprofil",
                "verbose_name_plural": "Mobile Nutzerprofile",
            },
        ),
        migrations.CreateModel(
            name="Aktion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wochentag",
                    models.IntegerField(
                        choices=[
                            (0, "Montag"),
                            (1, "Dienstag"),
                            (2, "Mittwoch"),
                            (3, "Donnerstag"),
                            (4, "Freitag"),
                            (5, "Samstag"),
                            (6, "Sonntag"),
                        ]
                    ),
                ),
                ("titel", models.CharField(max_length=200)),
                ("beschreibung", models.TextField(blank=True)),
                (
                    "kategorie",
                    models.CharField(
                        choices=[
                            ("programm", "Programm"),
                            ("mahlzeit", "Mahlzeit"),
                            ("schlaf", "Schlafen/Ruhe"),
                            ("hygiene", "Hygiene"),
                            ("transport", "Transport"),
                            ("frei", "Freie Zeit"),
                            ("sonstiges", "Sonstiges"),
                        ],
                        default="programm",
                        max_length=20,
                    ),
                ),
                ("beginn_stunde", models.IntegerField(help_text="0-23")),
                (
                    "beginn_minute",
                    models.IntegerField(default=0, help_text="0 oder 30"),
                ),
                ("ende_stunde", models.IntegerField(help_text="0-23")),
                ("ende_minute", models.IntegerField(default=0, help_text="0 oder 30")),
                ("ort", models.CharField(blank=True, max_length=200)),
                (
                    "verantwortlich",
                    models.ManyToManyField(
                        blank=True,
                        related_name="zugeordnete_aktionen",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wochenplan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aktionen",
                        to="mobile_api.wochenplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aktion",
                "verbose_name_plural": "Aktionen",
                "ordering": ["wochentag", "beginn_stunde", "beginn_minute"],
            },
        ),
    ]
