# Generated by Django 5.1.4 on 2026-07-02 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0006_alter_participant_options_and_more'),
        ('mobil', '0001_initial'),
        ('mobile_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gruppe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Gruppenname')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('aktionen', models.ManyToManyField(blank=True, related_name='gruppen', to='mobile_api.aktion', verbose_name='Aktionen')),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobil_gruppen', to='camps.camp')),
            ],
            options={
                'verbose_name': 'Gruppe',
                'verbose_name_plural': 'Gruppen',
                'ordering': ['name'],
                'unique_together': {('camp', 'name')},
            },
        ),
        migrations.AddField(
            model_name='freizeitmitglied',
            name='gruppe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mitglieder', to='mobil.gruppe', verbose_name='Gruppe'),
        ),
    ]
