# Generated by Django 5.1.4 on 2026-07-03 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0006_alter_participant_options_and_more'),
        ('mobil', '0002_gruppe_freizeitmitglied_gruppe'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreizeitZugang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='Zugangscode')),
                ('aktiv', models.BooleanField(default=True, verbose_name='Registrierung offen')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('camp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mobil_zugang', to='camps.camp')),
            ],
            options={
                'verbose_name': 'Freizeit-Zugangscode',
                'verbose_name_plural': 'Freizeit-Zugangscodes',
            },
        ),
    ]
