# Generated by Django 5.1.4 on 2026-07-05 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0006_alter_participant_options_and_more'),
        ('mobil', '0003_freizeitzugang'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkliste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200, verbose_name='Titel')),
                ('beschreibung', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('sichtbar_fuer', models.CharField(choices=[('alle', 'Alle'), ('supervisor', 'Nur Betreuer'), ('kitchen', 'Nur Küche'), ('leitung', 'Nur Leitung')], default='alle', max_length=20, verbose_name='Sichtbar für')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobil_checklisten', to='camps.camp')),
            ],
            options={
                'verbose_name': 'Checkliste',
                'verbose_name_plural': 'Checklisten',
                'ordering': ['titel'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistenPunkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='Punkt')),
                ('reihenfolge', models.PositiveIntegerField(default=0)),
                ('checkliste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punkte', to='mobil.checkliste')),
            ],
            options={
                'verbose_name': 'Checklisten-Punkt',
                'verbose_name_plural': 'Checklisten-Punkte',
                'ordering': ['reihenfolge', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='PunktErledigt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erledigt_am', models.DateTimeField(auto_now_add=True)),
                ('punkt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erledigungen', to='mobil.checklistenpunkt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklisten_haken', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Erledigter Punkt',
                'verbose_name_plural': 'Erledigte Punkte',
                'unique_together': {('punkt', 'user')},
            },
        ),
    ]
