# Generated by Django 5.1.4 on 2026-07-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riddle', '0002_text_solution_response'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='playerban',
            new_name='riddle_play_ip_addr_dec7b4_idx',
            old_name='riddle_playerban_ip_until_idx',
        ),
        migrations.AlterField(
            model_name='riddlestage',
            name='hint',
            field=models.TextField(blank=True, default='', help_text='Wird unterhalb des Bildes eingeblendet, wenn gesetzt.', verbose_name='Hinweis (optional)'),
        ),
    ]
