# Generated by Django 5.1.4 on 2026-05-14 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_ingredient_is_fresh"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="allergen",
            options={
                "ordering": ["sort_order", "name"],
                "verbose_name": "Allergen / Unverträglichkeit",
                "verbose_name_plural": "Allergene / Unverträglichkeiten",
            },
        ),
        migrations.AlterField(
            model_name="recipe",
            name="base_servings",
            field=models.PositiveIntegerField(
                default=10,
                help_text="Für wie viele Personen sind die Zutatenmengen angegeben?",
                verbose_name="Basis-Portionen",
            ),
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="unit",
            field=models.CharField(
                choices=[
                    ("g", "Gramm"),
                    ("kg", "Kilogramm"),
                    ("ml", "Milliliter"),
                    ("l", "Liter"),
                    ("Stk", "Stück"),
                    ("EL", "Esslöffel"),
                    ("TL", "Teelöffel"),
                    ("Pck", "Packung"),
                    ("Bd", "Bund"),
                ],
                default="g",
                max_length=10,
            ),
        ),
    ]
