# Generated by Django 5.1.4 on 2026-06-07 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0005_ingredient_diet_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipeingredient",
            name="unit",
            field=models.CharField(
                choices=[
                    ("g", "g"),
                    ("kg", "kg"),
                    ("ml", "ml"),
                    ("l", "l"),
                    ("Stk", "Stk"),
                    ("EL", "EL"),
                    ("TL", "TL"),
                    ("Pck", "Pck"),
                    ("Bd", "Bd"),
                ],
                default="g",
                max_length=10,
            ),
        ),
    ]
