# Generated by Django 5.1.4 on 2026-06-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0006_alter_recipeingredient_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Preis pro 'Preis-Einheit' unten, z.B. 5,36 für 5,36€ pro kg",
                max_digits=8,
                null=True,
                verbose_name="Preis (€)",
            ),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="price_unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("g", "g"),
                    ("kg", "kg"),
                    ("ml", "ml"),
                    ("l", "l"),
                    ("Stk", "Stk"),
                    ("EL", "EL"),
                    ("TL", "TL"),
                    ("Pck", "Pck"),
                    ("Bd", "Bd"),
                ],
                help_text="Auf welche Einheit sich der Preis bezieht (z.B. 'kg' bei 5,36€/kg)",
                max_length=10,
                verbose_name="Preis-Einheit",
            ),
        ),
    ]
